- name: Install Dnsmasq
  package: name=dnsmasq

- name: Copy dnsmasq config
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.d/consul

- name: Restart dnsmasq service
  systemd:
    name: dnsmasq
    state: restarted