- name: Install Dnsmasq
  package: name=dnsmasq

- name: Enable NetworkManager DNS plugin with dnsmasq
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    insertafter: '^\[main\]'
    line: dns=dnsmasq

- name: Copy dnsmasq config to NetworkManager config dir
  template:
    src: dnsmasq.conf
    dest: /etc/NetworkManager/dnsmasq.d/10-consul

- name: Restart NetworkManager service
  systemd:
    name: NetworkManager
    state: restarted