- name: Download consul
  get_url:
    url: "{{consul_url}}"
    dest: "{{consul_archive}}"

- name: Install unzip
  package: name=unzip

- name: Unzip archive
  become: yes
  become_user: root
  unarchive:
    src: "{{consul_archive}}"
    dest: /bin/
    remote_src: true
