- name: Create data directory
  file:
    path: "{{consul_data_dir}}"
    state: directory
    mode: 0700

- name: Create config directory
  file:
    path: /etc/consul.d
    state: directory
    mode: 0755

- name: Create system.d service template
  template:
    src: consul.service
    dest: /etc/systemd/system/

- name: Copy basic nomad config
  template:
    src: config.json
    dest: /etc/consul.d/

- name: Copy server config
  when: is_consul_master
  template:
    src: server.json
    dest: /etc/consul.d/

- name: Copy client config
  when: not is_consul_master
  template:
    src: client.json
    dest: /etc/consul.d/

- name: Create service
  systemd:
    name: consul
    enabled: true
    daemon_reload: true
    state: restarted
