# -*- mode: ruby -*-
# vi: set ft=ruby :

number_of_nodes = 2

def get_node_ip(i)
  "192.168.100.#{i}"
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  master_offset = 10
  (0...number_of_nodes).each do |i|
    config.vm.define "node#{i}" do |node|
      is_master = i == 0
      node_ip = get_node_ip(i + master_offset)

      node.vm.network "private_network", ip: node_ip

      # forward nomad HTTP port
      if is_master
        node.vm.network "forwarded_port", guest: 4646, host: 4646
      end

      config.vm.provision "shell", inline: "test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)"
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/main.yml"
        ansible.extra_vars = {
          vagrant: true,
          node_ip: node_ip,
          node_name: "node#{i}",
          is_consul_master: is_master,
          join_consul_cluster_ip: get_node_ip(master_offset),
        }
      end    
    end
  end
end
