- name: Download nomad
  get_url:
    url: "{{nomad_download_url}}"
    dest: "{{nomad_archive}}"

- name: Install unzip
  package: name=unzip

- name: Unzip archive
  become: yes
  become_user: root
  unarchive:
    src: "{{nomad_archive}}"
    dest: /bin/
    remote_src: true
