- hosts: all
  become: yes
  become_user: root
  roles:
    - role: vagrant
      when: vagrant
    - consul
    - nomad

  tasks:
    - name: Install docker
      package: name=docker
    - name: Start docker
      systemd:
        name: docker
        enabled: true
        state: started
    